[phases.install]
cmds = [
  "composer install --optimize-autoloader --no-scripts --no-interaction --ignore-platform-reqs --no-plugins"
]

[phases.build]
cmds = [
  "npm ci --prefer-offline",
  "npm run build"
]

[start]
cmd = "sh start.sh"
