[phases.install]
cmds = [
  "composer install --optimize-autoloader --no-scripts --no-interaction --ignore-platform-reqs"
]

[phases.build]
cmds = [
  "npm ci",
  "npm run build",
  "chmod +x start.sh"
]

[start]
cmd = "sh start.sh"
